backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'personal'
    label: 'Personal'
    files:
      - file: 'src/assets/content/portfolio.md'
        label: 'Portfolio Projects'
        name: 'portfolio'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'portfolio',
            }
          - { label: Title, name: title, widget: hidden, default: 'portfolio' }
          - label: Projects
            name: projects
            widget: list
            fields:
              [
                { label: Title, name: title, required: false, widget: string },
                { label: Image, required: false, name: image, widget: image },
                {
                  label: Description,
                  required: false,
                  name: description,
                  widget: text,
                },
                { label: Link, required: false, name: url, widget: string },
                {
                  label: 'Technology (Keep name exactly same to prevent newer tabs)',
                  name: technology,
                  required: false,
                  widget: string,
                },
              ]
